# APARAVI MCP Server Configuration Example
# Copy this file to config.yaml and customize as needed

aparavi:
  host: "localhost"
  port: 80
  username: "root"
  password: "root"
  api_version: "v3"
  timeout: 30
  max_retries: 3

server:
  name: "aparavi-mcp-server"
  version: "0.1.0"
  log_level: "INFO"
  cache_enabled: true
  cache_ttl: 300
